PULL_REQUEST_TEMPLATE.md, README.md
Work carried out was to create a Pull Request template for the development team so that we had consistency when submitting pull requests. I also created an initial Read me file in which we can update in time with important information
[x] This change requires a documentation update
How Has This Been Tested?
Use the template as part of this PR 
[x] My code follows the style guidelines of this project
[x] I have performed a self-review of my own code
[N/A] I have commented on my code, particularly in hard-to-understand areas
[x] I have made corresponding changes to the documentation (if required)
[x] My changes generate no new warnings
[N/A] I have added tests that prove my fix is effective or that my feature works
[N/A] New …
=> Creation of PR Template markdown file and Readme file

app/src/Components/Project/ProjectReturnedList.tsx, app/src/Components/Project/ProjectSummary.tsx
- Refactored to FlatList which has some advantages over ScrollView, with performance advantages being the most important, especially for longer lists, and some out of the box features such as pull to refresh etc. 
- Please note: this is a sub-branch for branch SVA-116 to create a Project Detail Component 
- [] Bug fix (non-breaking change which fixes an isssue)
- [] I have commented my code, pariculary in hard-to-understand areas
- [] I have added tests that prove my fix is effective or that my feature …
=> refactor main project list to FlatList

api/routes/projects.js
- Amended API call for the IT board to return only the data in 'Volunteer Search', 'Volunteer Introduction' and 'Activity Underway'.
Fixes # [SVA-133](https://sta2020.atlassian.net/browse/SVA-133)
- [] Bug fix (non-breaking change which fixes an isssue)
=> Feature/SVA-133 | Return data in relevant project columns

app/src/Components/Project/ProjectReturnedList.tsx, app/src/Components/Project/ProjectSkills.tsx, app/src/Components/Project/ProjectSummary.tsx, app/src/Containers/HomeContainer.tsx, app/src/Services/modules/projects/fetchAll.ts, app/src/Services/modules/projects/index.ts
- This wires the project list in the app to the back-end API, where it was using seed data. 
Fixes [SVA-137](https://sta2020.atlassian.net/browse/SVA-137)
- [] Breaking change(fix or feature that would cause existing functionlity to not work as expected)
- [] I have commented my code, pariculary in hard-to-understand areas
- [] New and existing unit tests pass locally with my changes
=> Feature/SVA-137 | wire backend to frontend

README.md
- Update Readme file to include:
- run npm install and npm start in api folder to run Metro in separate terminal window
- create .env file to store Jira API access credentials. 
> NB credentials themselves not provided, these should be requested/provided on joining the dev group.
Fixes #[SVA-141](https://sta2020.atlassian.net/browse/SVA-141)
- [] I have commented my code, pariculary in hard-to-understand areas
- [] My changes generate no new warnings
- [] New and existing unit tests pass locally with my changes
=> feature/SVA-141 | update Readme file

api/data.json, api/routes/projects.js
- This change ensures that static dummy data is loaded to run the app if Jira API credentials are wrong or missing (rather than being stuck in "Loading...." screen).
- For front-end development it is not necessary to have access to the Jira API. 
Fixes #[SVA-143](https://sta2020.atlassian.net/browse/SVA-143)
- [] New Feature (non-breaking change which adds functionlity)
- [] Breaking change(fix or feature that would cause existing functionlity to not work as expected)
- [] I …
=> Feature/SVA-143 | Load dummy data if no access to JiraAPI

api/__test-data__/projects.js, api/__tests__/cache/projects.test.js, api/cache/projects.js, api/definitions/api_definition.json, api/sample-data/projects.json
Fixes # [issue number](https://sta2020.atlassian.net/browse/SVA-175)
- Added A3 Scope Doc to the Jira Project Data array
- [] Bug fix (non-breaking change which fixes an isssue)
- [] Breaking change(fix or feature that would cause existing functionlity to not work as expected)
- [] I have commented my code, pariculary in hard-to-understand areas
- [] New and existing unit tests pass locally with my changes
=> SVA-175 | Added A3 Scope Jira field

app/src/Components/Project/ProjectAttachments.tsx, app/src/Components/Project/ProjectHeading.tsx, app/src/Components/Project/ProjectInterestButton.tsx, app/src/Components/Project/ProjectOptions.tsx, app/src/Components/TopOfApp.tsx, app/src/Containers/SearchContainer.tsx, app/src/Utils/UnderDevelopmentAlert.ts
- Adds an alert to several touchables to indicate that a feature is currently to be developed
=> SVA-171 - Add under development alert

.github/workflows/ci_app.yml, app/scripts/createConfig.sh
The front end test was failing because the config file was missing. Added a script to create this file from the example one.
Fixes SVA-180
=> SVA-180 - Add script to create config file

app/ios/Podfile.lock, app/src/Containers/HomeContainer.tsx, app/src/Containers/ProjectSearchResultsContainer.tsx, app/src/Containers/SearchContainer.tsx, app/src/Services/modules/projects/index.ts
- Add search functionality to the quick search buttons for charity sectors (causes). 
Fixes # ([SVA-42](https://sta2020.atlassian.net/browse/SVA-42))
- [] New and existing unit tests pass locally with my changes
=> Sva 42 search by charity sector

app/package-lock.json, app/src/Translations/resources/en.ts
Replaced default welcome message with an STA one.
- Replaced default welcome text from boilerplate with "Welcome to the Scottish Tech Army App"
Fixes issue raised at Team Meeting on 20-Jul-22.
- X[] My code follows the style guidelines of this project
- [] I have added tests that prove my fix is …
=> Changed welcome message

README.md
- Improves the setup and deployment instructions for Google Play Store
- Fixes wrong instructions about keystore file
- Adds a few more helpful things
- Makes instructions clearer
Fixes [SVA-212](https://sta2020.atlassian.net/jira/software/projects/SVA/boards/145?selectedIssue=SVA-212)
=> SVA-212 | Fixes and improvements to Google Play setup and deployment instructions

app/src/Containers/ExampleContainer.tsx
Added links to STA privacy policy and terms & conditions at bottom of user account screen (ExampleContainer).  These links open in external browser on the user's device when clicked.
SVA-201
=> SVA 201 Add STA Contact Details

app/android/app/build.gradle
- Updated the version code for Android deployment 
Fixes # ([SVA-218](https://sta2020.atlassian.net/browse/SVA-218))
=> SVA-218 | Updated version code

DEPLOYMENT.md
- Updated deployment instructions -- currently this looks like the easiest, hopefully foolproof way to deploy API changes
- As part of testing this, if you have access to our AWS account, please can you try it yourself as a double-check that it works
Fixes SVA-221
- [] My changes generate no new warnings
=> SVA-221 | Update API deployment instructions on how to safely deploy to AWS

app/src/Containers/ExampleContainer.tsx
- Prettier changing camelCase with flagrant disregard for eslint rules!!
Fixes # 102
- []X New and existing unit tests pass locally with my changes
=> Stupid Prettier.

app/.prettierrc.js
Turn off the embeddedLanguageFormatting Prettier rule. This should prevent the issue in @DougieWougie's PR from recurring. See https://prettier.io/blog/2020/08/24/2.1.0.html
- [] New and existing unit …
=> Stop the issue in PR #103 from recurring

DEPLOYMENT.md, app/android/app/build.gradle
- Updated the build number for Android and a small update to the deployment known issues
Fixes # ([SVA-253](https://sta2020.atlassian.net/browse/SVA-253))
=> Build number and Deployment updates

app/android/app/src/main/AndroidManifest.xml, app/android/build.gradle
- Google has updated their API: https://developer.android.com/google/play/requirements/target-sdk as of November 2022
- Updates required to SDK version in build.gradle and AndroidManifest.xml to be able to deploy to Google Play. 
```
compileSdkVersion = 30
targetSdkVersion = 30
```
to 
```
compileSdkVersion = 31
targetSdkVersion = 31
```
And 
`android:exported="true"> `to be added to AndroidManifest.xml & set to true. Emulator does not launch if set to false: https://developer.android.com/guide/topics/manifest/activity-element#exported
Fixes # ([SVA-254](https://sta2020.atlassian.net/browse/SVA-254))
- [] I have commented my code, particularly in …
=> Google Play Updates for Android Deployment

SECURITY.md
- Added SECURITY.md
- Add here anything someone would need to do to test your code locally, or delete this section if nothing needed
- E.g. run `npm install` in the app, refresh the database, look at a particular project that has a video, add a `.env` file value (NB do not share any sensitive details here as PRs are public)
- [] I have checked the app in dark mode, if making front-end design changes
- [] I have added tests that prove my fix is effective or that my …
=> Added vulnerabilities reporting address

DEPLOYMENT.md, README.md, api/.dockerignore, api/Dockerfile, api/package-lock.json, api/package.json, api/server.js
- Cron jobs
- Added Dockerfile and .dockerignore
Fixes # SVA-224
- Is it this simple?
- I've created Docker container so that if it isn't then I just add to crontab plus Docker is easier than faffing about zipping files and can be automated through GitHub Actions.
- [] I have checked the app in dark mode, if making front-end design changes
=> Run cron jobs from server.

app/package-lock.json, app/src/NativeBase/Components/Project/ProjectRegisterInterest.tsx, app/src/NativeBase/Containers/ProjectRegisterInterestContainer.tsx
- Moved the ScrollView from ProjectRegisterInterestContainer to ProjectRegisterInterest because (a) it allows the button to remain in the same postion and (b) if additional components are added to the form, the previous paradigm left the button floating on top of other components.
- Doesn't change any dependencies.
Fixes #SVA-291
- [] I have added …
=> Fixes SVA#291 - Register Interest Button not fixed in position

DEPLOYMENT.md
- Just fixing API URLs in the deployment readme -- this being out of date caused an issue with a recent app deployment
- Nothing to test
=> SVA-286 | Fix API URLs in deployment readme

api/cron-jobs/events.js, api/cron-jobs/projects.js
-  Added some try catch loops around the Axios calls in the cron jobs, so that they stop and log an error if one is  thrown when attempting to pull initial triage and project data from the database.
Fixes # SVA-283
- [] New Feature (non-breaking change which adds functionality) - Non breaking change, but not a feature, just cron job error handling
=> Sva 283 add error handling to axios calls

.github/workflows/ci_app.yml
- Replaced ubuntu-latest Docker image with alpine-node
- Jest completes correctly with alpine-node
- alpine-node is significantly smaller, speeding up CI
Fixes # SVA-299
- Test locally using nekos/act but specify the specific yaml file using "act -j lint -W .github/workflows/ci_app.yml"
=> Replaced ubuntu-latest with alpine-node 🐛 💚 

README.md
- Readme update after setup troubleshooting
- Feature/update
- Tested readme for formatting
- Added tips in setup section:
- tested Ruby version compatible with RN
- `bundle install` prior to `pods install`
- command for killing an old server
- Adjusted formatting
- Check Readme for formatting
=> Readme troubleshooting section update

app/src/NativeBase/Components/Forms/DatePicker.tsx, app/src/NativeBase/Components/Project/ProjectRegisterInterest.tsx
- A fix making calendar pressable on iOS - [stackoverflow tip](https://stackoverflow.com/questions/54707607/how-to-setup-onpress-on-textinput-in-react-native)
- Removed old component import while in another file
Fixes # [SVA-290](https://sta2020.atlassian.net/browse/SVA-290)
- Run on iOS and Android to check for calendar showing correctly
- [] I have commented my code, particularly in hard-to-understand …
=> SVA-290 Calendar fix iOS

.github/workflows/ci_app.yml
- Fixes CI but replaces node-alpine with Ubuntu 20.04
- [] I have followed best practices, e.g. NativeBase approaches and theming
- [] I have checked the app in dark …
=> Switched to Ubuntu 20.04 💚 

.github/workflows/ci_app.yml, app/package-lock.json, app/src/NativeBase/Components/Project/ProjectFullDetails.tsx
- Fixes crashes on Android devices with smaller screens where Project Detail pushes Register Interest Button out of view.
- Fixes Button at the bottom of the view, regardless of the amount of text, in line with designers intent.
- Fixes thumbreach issue with Projects with less information.
Fixes # SVA-300 (App crashes when scrolling Projects with large amounts of info)
- [] I have made corresponding …
=> Moved Button outside ScrollView and changed margin 🐛 💄 

app/src/NativeBase/Components/TopOfApp.tsx
-Corrected sizing for top nav bar. Pixel values could not be used due to the nature of the component, but the component was made consistent with the bottom nav bar.
NOTE: Will need to check consistency with IOS devices before approving the request.;
Fixes # SVA-295
- [] I have performed a self-review of my own code
- [] I have addressed …
=> corrected top nav bar sizing

.github/workflows/ci_app.yml
- Works with ubuntu-latest, so should won't need to be manually updated.
- Updated checkout action
- Specific Node version
Fixes # SVA-299
- Tested with nekos/act
- Tested with dummy PR - ignore ESLint as I used the first PR that didn't complete CI.
- [] I have followed best practices, …
=> Fix App CI 🐛 💚 

app/src/NativeBase/Components/SegmentedPicker.tsx, app/src/NativeBase/Theme/StaTheme.tsx
The segmented picker (See the Testing locally section for the locations of this component) did not update to dark mode colours in dark mode, which is different to the Figma design.
Added the styling changes necessary to make this happen. In some cases where there is no preset colour style in the NativeBase styling, I used a hex colour value inline in the code. This was either because the element (divider in this case) had opacity styling and this was the simplest solution, or it was a one time colour use. Happy to update if required.
Fixes # SVA-307
- Load up the app in an emulator or similar, and check that the segmented picker updates its colours when changed …
=> Update to colours to change on dark mode.

.github/workflows/cd_api.yml
- Updated Continuous Deployment details following changes to Elastic Beanstalk environment.
=> Updated EB Details 💚 

app/ios/Podfile
- Ran into issues deploying IOS after upgrading to Xcode 14 - other folk have be encountering similar issues: https://github.com/facebook/react-native/issues/34673
- One solution was to add a script to the Podfile to specify Team ID (deploy was then successful)
- Team ID can be found on the apple developer website https://developer.apple.com/account/#/membership under the menu "Certificates, Identifiers & Profiles" and then look at the top right under your account name. Will usually be a mix of letters and numbers.
Fixes # [(SVA-232)](https://sta2020.atlassian.net/browse/SVA-232)
- …
=> Changes to Podfile for IOS deployment

app/src/Navigators/Main.tsx
- Commented out the profile tab and removed the import
- Checked the Profile tab is not showing on the bottom panel
Fixes # [SVA-368](https://sta2020.atlassian.net/browse/SVA-368?atlOrigin=eyJpIjoiMTVhZGUzNTM4NTEyNDAwOGFkN2FmOGIyZTdkN2JkMDYiLCJwIjoiaiJ9)
- Run the Volunteer app on expo and see if Profile tab is not visible anymore
- [] I have …
=> Hide Profile tab and container

api/__tests__/helpers/urls.test.js, api/helpers/urls.js
- The urls and emails in the description are occasionally wrapped in square brackets with some additional unwanted text. This has been fixed in the previous PR, using regex in the backend. 
- This PR is to further include urls that have a space in them. 
- run the app using expo and check the urls are looking as they should and not wrapped in square brackets.
=> SVA-316 update regex to clean up links further

DEPLOYMENT.md, PULL_REQUEST_TEMPLATE.md, README.md, app/app.config.ts, app/deployment/.gitignore, app/eas.json, app/package.json
- Make app version numbering easier by getting Expo Application Services to handle it automatically
- Make Google Play Store deployment easier by not needing to store credentials files locally
- Improvements to deployment instructions and other docs
Fixes # SVA-271 & SVA-272
N/A
- [] I have checked the app in dark mode, if making front-end design changes
- [] If updating the API, I have updated the API version number to prepare for me to …
=> SVA-271 & SVA-272 | Updates for deployment to Google Play Store and App Store

README.md
…tunnel subdomain
Updated Readme with additonal information and clarification on ensuring the STA_BASE_URL and API_TUNNEL_SUBDOMAIN are set corretly to avoid loading issues on Expo.
- Add here anything someone would need to do to test your code locally, or delete this section if nothing needed
- E.g. run `npm install` in the app, …
=> Update to Readme. Clarification on tunnel and base URL info

README.md
- A line clarifying `npx expo install` should be run if using `--legacy-peer-deps` flag
Fixes #N/A
N/A
- [] I have performed a self-review of my own code
- [] I have followed best practices, e.g. NativeBase approaches and …
=> Add comment about manually installing Expo

README.md, api/package-lock.json, api/package.json
- @vglampard  has been having problems getting the API tunnelling command to work on Windows.  This could affect other devs too and we want to make getting set up as simple and pain-free as possible.
- Updated the API tunnelling command to probably be more reliable generally, by using `cross-var` and `dotenv-cli` packages, so we can have a single command that works across different machines.
Fixes # SVA-382
@vglampard has already tried this out on her Windows machine and I have on Linux - be great to get it tested on at least one other Windows machine, and on a Mac
- Pull this branch then in your `api` directory do …
=> SVA-382 | Fix API tunnelling bug on some Windows machines

app/package-lock.json, app/src/NativeBase/Components/ChoicesList.tsx, app/src/NativeBase/Components/Forms/DatePicker.tsx, app/src/NativeBase/Components/Forms/YesNoChoice.tsx, app/src/NativeBase/Components/Project/ProjectFullDetails.tsx, app/src/NativeBase/Containers/ProfileContainer.tsx, app/src/NativeBase/Containers/ProjectSearchContainer.tsx, app/src/NativeBase/Containers/VerticalStackContainer.tsx, app/src/NativeBase/Theme/StaTheme.tsx, app/src/Navigators/Main.tsx
- This adds content to the Profile screen container, with placeholder content for user details
- menu items ready to be connected to new screens 
Fixes # (SVA-386)[https://sta2020.atlassian.net/browse/SVA-386]
- run locally and check it looks as per design
- [] I have updated the version numbers in `package.json` files in the [app](DEPLOYMENT.md#app-deployment) and/or [api](DEPLOYMENT.md#api-deployment-on-aws) …
=> feature/SVA-386 add placeholder content to Profile screen container

GITFLOW.md, README.md
Added instructions on Git Flow.
- Git Flow configuration steps
If you're unsure, feel free to create your own Git Hub repository and play around with the commands and configuration!
=> Added Git Flow instructions

api/package-lock.json, app/package-lock.json, app/src/Components/Welcome/WelcomeButton.tsx, app/src/NativeBase/Components/ChoicesList.tsx, app/src/NativeBase/Components/ColouredTag.tsx, app/src/NativeBase/Components/Forms/DatePicker.tsx, app/src/NativeBase/Components/Forms/YesNoChoice.tsx, app/src/NativeBase/Components/List.tsx, app/src/NativeBase/Components/NavigationHeader.tsx, app/src/NativeBase/Components/Project/ProjectFullDetails.tsx, app/src/NativeBase/Containers/ProfileContainer.tsx, app/src/NativeBase/Containers/ProjectSearchContainer.tsx, app/src/NativeBase/Containers/SettingsContainer.tsx, app/src/NativeBase/Theme/StaTheme.tsx
- Throughout the app many different font sizes and paddings/margins were being set. This makes some changes to a few of the Theme components to standardise and avoid need for corrective margins or negative padding. 
- Biggest impact requiring some margin and padding changes on all screens was removing the default padding from the `Text` component
- Other change worth noting is introducing a way to easily set the font style following the naming in the Design System in Figma. 
- Refactored codebase to ensure layout is preserved
- Overall there should now be less margins and paddings set throughout the codebase and no more need for negative padding. 
- Also …
=> SVA-387 Update theme components and refactor code to match

package.json, src/NativeBase/Components/PrivacyAndTermsLinks.tsx, src/NativeBase/Theme/StaTheme.tsx
- Ignores the device text size so that users with larger text sizes set won't be blocked from accessing the app. This is a temporary workaround until we determine the approach we want to take for making the app more accessible. 
Fixes # [SVA-422](https://sta2020.atlassian.net/browse/SVA-422
- Enable the largest text size on your device. [Iphone ](https://support.apple.com/en-sa/guide/iphone/iph3c076905a/ios#:~:text=Make%20text%20easier%20to%20read&text=Go%20to%20Settings%20%3E%20Accessibility%20%3E%20Display,to%20show%20more%20size%20options) | [Android](https://support.google.com/accessibility/android/answer/11183305? …
=> SVA-422/ignoreDeviceTextSize

eas.json
- Please include a summary of the change and which issue is fixed.
- List any dependencies that are required for this change.
- Add here anything someone would need to do to test your code locally, or delete this section if nothing needed
- E.g. run `npm install` in the app, refresh the database, look at a particular project that …
=> Update EAS config

app.config.ts, src/Services/modules/projects/fetchAll.ts
- First version of switching from former airtable lambda backend to dynamo db based lambda backend
- See if the data differs from the production backend which still relies on airtable.
- [] I have performed a self-review of my own code
- [] I have addressed …
=> change projectlist to dynamo db backend
